const container = require('kontainer-di')
const Hapi = require('hapi')
const mongoose = require('mongoose')
const good = require('good')
const joi = require('joi')
const boom = require('boom')
const Expense = require('../models/expense')
const config = require('./properties')
const routes = require('./routing')
const expenseController = require('../controllers/expense')
const db = require('./db')

container.register('Hapi', [], Hapi)
container.register('good', [], good)
container.register('mongoose', [], mongoose)
container.register('joi', [], joi)
container.register('boom', [], boom)
container.register('config', [], config)
container.register('db', ['mongoose', 'config'], db)
container.register('Expense', ['mongoose'], Expense)
container.register('expenseController', ['joi', 'boom', 'Expense'], expenseController)
container.register('routes', ['expenseController'], routes)

module.exports = container
